# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class AccountSection(StrEnum):
    ACTIVE = auto()
    SPAM = auto()
    FROZEN = auto()

__all__ = (
    "AccountSection", 
)
