# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class AccountOperation(StrEnum):
    SELL = auto()
    BUY = auto()

__all__ = (
    "AccountOperation", 
)
