# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class BalanceType(StrEnum):
    SELL = auto()
    BUY = auto()
    REFERRAL = auto()

__all__ = (
    "BalanceType", 
)
