# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class BuySessionType(StrEnum):
    PYROGRAM = auto()
    PYROGRAM_STRING = auto()
    KURIGRAM = auto()
    KURIGRAM_STRING = auto()
    TELETHON = auto()
    TELETHON_STRING = auto()
    TDATA = auto()

__all__ = (
    "BuySessionType", 
)
