# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class OrderStatus(StrEnum):
    PENDING = auto()
    PROCESSING = auto()
    DELIVERING = auto()
    DELIVERED = auto()
    CANCELLING = auto()
    CANCELLED = auto()

__all__ = (
    "OrderStatus", 
)
