# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class SellAccountStat(StrEnum):
    CODE_CHECKING = auto()
    PASSWORD_CHECKING = auto()
    WAIT_CHECKING = auto()
    ACTIVE = auto()
    RESERVED = auto()
    SESSION_RESERVED = auto()
    DELIVERED = auto()

__all__ = (
    "SellAccountStat", 
)
