# This file is auto-generated by the schema generator.
# Do not edit manually.

from enum import auto

from .._compat import StrEnum

class SendCodeType(StrEnum):
    APP = auto()
    EMAIL = auto()

__all__ = (
    "SendCodeType", 
)
