[project]
name = "WolfTg"
dynamic = ["version"]
description = "Official Python SDK for the WolfTg API."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Abdullah", email = "aldheeb01@gmail.com" }
]

license = { text = "MIT" }

keywords = [
    "wolftg",
    "wolf-tg",
    "telegram",
    "telegram-api",
    "api",
    "sdk",
    "client",
    "asyncio",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",

    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Framework :: AsyncIO",

    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "requests>=2.32,<3.0",
    "pydantic>=2.7,<3.0",
    "aiohttp[speedups]>=3.9,<4.0",
    "aldheeb-pytools[country,phone]>=0.2.15",
]

[project.urls]
Homepage = "https://github.com/eeeob/WolfTg"
Repository = "https://github.com/eeeob/WolfTg"
Issues = "https://github.com/eeeob/WolfTg/issues"
API = "https://wolf-tg.com/api/docs"


[project.optional-dependencies]
dev = [
    "hatch>=1.16,<2.0",
    "twine>=6.1,<7.0",
]


[tool.hatch.build.targets.sdist]
exclude = [".github/"]

[tool.hatch.version]
path = "WolfTg/__meta__.py"


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["WolfTg"]
