# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..enums import AccountOperation, AccountSection
from ..types import AvailableCountriesBySectionResult
from .base import ApiMethod

class AvailableCountriesBySection(ApiMethod[AvailableCountriesBySectionResult]):
    """List the countries currently open for trading within a single quality tier.

    Same data as AvailableCountries, narrowed to `section` and returned flat: keyed by
    country code instead of grouped by tier.
    """

    __returning__ = AvailableCountriesBySectionResult
    __request_method__ = "GET"

    operation: AccountOperation
    """Which side of the market to query: 'sell' lists countries open for selling, 'buy' lists countries with accounts in stock."""

    section: AccountSection
    """Quality tier to narrow the country listing to."""

__all__ = (
    "AvailableCountriesBySection", 
)
