# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..enums import AccountOperation
from ..types import AvailableCountriesResult
from .base import ApiMethod

class AvailableCountries(ApiMethod[AvailableCountriesResult]):
    """List the countries currently open for trading, grouped by quality tier.

    With `operation=sell` each country maps to its selling price. With `operation=buy`
    each country maps to a stock info document describing what is available to buy.
    """

    __returning__ = AvailableCountriesResult
    __request_method__ = "GET"

    operation: AccountOperation
    """Which side of the market to query: 'sell' lists countries open for selling, 'buy' lists countries with accounts in stock."""

__all__ = (
    "AvailableCountries", 
)
