# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..utils.typings import ValidRegionCode
from ..enums import AccountSection
from ..types import BuyAccountResult
from .base import ApiMethod

class BuyAccount(ApiMethod[BuyAccountResult]):
    """Buy a single Telegram account from the given country and quality tier.

    Reserves an available account, charges the buyer's balance (after applying any
    eligible discount) and returns the reserved phone number. The login code is not
    delivered here — the buyer retrieves it separately via GetCodeAccount.

    On any failure after reservation, the reservation is released and the charge refunded.

    Raises:
        UserBannedFromBuying: (403) You are banned from buying accounts. Ban duration: {value}s
        AccountForBuySectionClosed: (409) Buying is not allowed for {context[country]} country {context[section]} account section at the moment
        AccountPurchaseAttemptsExhausted: (409) All purchase attempts have been exhausted without acquiring an account
        InsufficientBalance: (409) You are does not have enough balance for this operation
        NoAccountsAvailableForCountry: (409) No accounts available for purchase in this country
    """

    __returning__ = BuyAccountResult
    __request_method__ = "GET"

    country_code: ValidRegionCode
    """ISO 3166-1 alpha-2 country code. Case-insensitive on input, normalized to lowercase."""

    section: AccountSection
    """Quality tier of the account to buy. Determines pricing and availability."""

__all__ = (
    "BuyAccount", 
)
