# This file is auto-generated by the schema generator.
# Do not edit manually.

from pydantic import Field

from ..utils.typings import ValidRegionCode
from ..enums import AccountSection, BuySessionType
from ..types import BuySessionsResult
from .base import ApiMethod

class BuySessions(ApiMethod[BuySessionsResult]):
    """Place a bulk order for ready-made Telegram session files.

    Reserves up to `qty` accounts from the given country and quality tier, charges the
    buyer's balance and queues the order for background processing. Returns immediately
    with the order record; delivery progress is polled via GetBuySessionsOrder.

    When `force_full` is set, the order is rejected unless the full quantity is available.
    On any failure before the order is queued, reservations are released and the charge
    refunded.

    Raises:
        UserBannedFromBuying: (403) You are banned from buying accounts. Ban duration: {value}s
        AccountForBuySectionClosed: (409) Buying is not allowed for {context[country]} country {context[section]} account section at the moment
        InsufficientBalance: (409) You are does not have enough balance for this operation
        NoAccountsAvailableForCountry: (409) No accounts available for purchase in this country
    """

    __returning__ = BuySessionsResult
    __request_method__ = "GET"

    country_code: ValidRegionCode
    """ISO 3166-1 alpha-2 country code. Case-insensitive on input, normalized to lowercase."""

    qty: int = Field(gt=0)
    """Number of sessions to order. Must be greater than zero."""

    section: AccountSection
    """Quality tier of the sessions to buy. Determines pricing and availability."""

    session_type: BuySessionType
    """Session file format to deliver. The '*_string' variants return a session string instead of a file."""

    force_full: bool = False
    """When true, the order fails unless the full requested quantity can be delivered; otherwise a partial delivery is accepted."""

    include_json: bool = False
    """When true, a JSON metadata file is delivered alongside each session."""

__all__ = (
    "BuySessions", 
)
