# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..types import GetBalanceResult
from .base import ApiMethod

class GetBalance(ApiMethod[GetBalanceResult]):
    """Return the caller's wallet balances, broken down by type, along with their total."""

    __returning__ = GetBalanceResult
    __request_method__ = "GET"

__all__ = (
    "GetBalance", 
)
