# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..utils.typings import ValidPhoneNumber
from ..types import GetSellAccountStatResult
from .base import ApiMethod

class GetSellAccountStat(ApiMethod[GetSellAccountStatResult]):
    """Report where a seller's account currently stands in the sell flow.

    Only the seller who registered the account may query it. Answers for three stages
    only — awaiting a login code, awaiting a two-step password, or under automated
    checking — and reports the attempts, remaining time, password hint or checking
    deadline relevant to that stage. Any other state, including an unregistered number,
    is rejected rather than reported.

    Raises:
        InvalidSellerAccountOwner: (403) You are not the owner of this sold account
        InvalidSellSessionStat: (409) Sell session is not in a valid stat to perform this operation
    """

    __returning__ = GetSellAccountStatResult
    __request_method__ = "GET"

    phone_number: ValidPhoneNumber
    """Telegram account phone number in international E.164 format, including the leading '+'."""

__all__ = (
    "GetSellAccountStat", 
)
