# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..utils.typings import ValidRegionCode
from ..types import GetCountryInfoResult
from .base import ApiMethod

class GetCountryInfo(ApiMethod[GetCountryInfoResult]):
    """Describe one country: its identity and its full buy/sell terms per quality tier.

    Buy terms carry the price and the quantity currently in stock; sell terms carry the
    price and the automated checking duration. Fields are omitted where the tier is
    closed, out of stock, or unconfigured.
    """

    __returning__ = GetCountryInfoResult
    __request_method__ = "GET"

    country_code: ValidRegionCode
    """ISO 3166-1 alpha-2 country code. Case-insensitive on input, normalized to lowercase."""

__all__ = (
    "GetCountryInfo", 
)
