# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..utils.typings import ValidPhoneNumber
from ..types import GetCodeAccountResult
from .base import ApiMethod

class GetCodeAccount(ApiMethod[GetCodeAccountResult]):
    """Retrieve the Telegram login code and two-step password for a purchased account.

    Only the buyer who reserved the account may call this, and only while it is still
    reserved. Each call consumes one attempt. On success the account session is logged
    out and handed over to the buyer.

    If the account is found dead during retrieval the purchase is refunded — unless the
    attempt budget is already exhausted, in which case no refund is issued.

    Raises:
        InvalidBuyerAccountOwner: (403) You are not the owner of this buy account
        NotFoundOtpCode: (404) OTP code is not available for this session at the moment
        AccountDeadDuringGetCode: (409) Account became dead during code retrieval process
        InvalidSellSessionStat: (409) Sell session is not in a valid stat to perform this operation
        UnknowError: (500) Unknow error occurred. Error: {context}
    """

    __returning__ = GetCodeAccountResult
    __request_method__ = "GET"

    phone_number: ValidPhoneNumber
    """Telegram account phone number in international E.164 format, including the leading '+'."""

__all__ = (
    "GetCodeAccount", 
)
