# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..types import GetBuySessionsOrderResult
from .base import ApiMethod

class GetBuySessionsOrder(ApiMethod[GetBuySessionsOrderResult]):
    """Poll the progress of a previously placed sessions order.

    Returns the same order record as BuySessions, with `status` and `ready_count`
    reflecting current delivery progress. Only the buyer who placed the order may read it.

    Raises:
        OrderAccessDenied: (401) You are not authorized to access this order
        OrderNotFound: (404) Order {value} not found
    """

    __returning__ = GetBuySessionsOrderResult
    __request_method__ = "GET"

    order_id: str
    """24-character hexadecimal MongoDB ObjectId identifying a buy-sessions order."""

__all__ = (
    "GetBuySessionsOrder", 
)
