# This file is auto-generated by the schema generator.
# Do not edit manually.

from typing import Optional

from ..utils.typings import ValidPhoneNumber
from ..enums import AccountSection
from ..types import SellAccountResult
from .base import ApiMethod

class SellAccount(ApiMethod[SellAccountResult]):
    """Start selling a Telegram account by requesting its login code.

    Opens a session against the given number and asks Telegram to send a login code,
    then returns the delivery channel, the attempt budget and the expiry deadline.
    The seller completes the flow by submitting that code via SetCodeAccount.

    The account is released automatically if the code is not confirmed before expiry.

    Raises:
        UserBannedFromSelling: (403) You are banned from selling accounts. Ban duration: {value}s
        PhoneNumberUnoccupied: (404) The phone number is not registered on Telegram
        AccountForSellSectionClosed: (409) Selling is not allowed for {context[country]} country {context[section]} account section at the moment
        SellAccountStatAlreadyExists: (409) A sell process already exists for this account
        SessionAlreadyExists: (409) A session already exists for this phone number
    """

    __returning__ = SellAccountResult
    __request_method__ = "POST"

    phone_number: ValidPhoneNumber
    """Telegram account phone number in international E.164 format, including the leading '+'."""

    section: Optional[AccountSection] = None
    """Expected quality tier of the account being sold. When omitted, the tier is resolved automatically during checking."""

__all__ = (
    "SellAccount", 
)
