# This file is auto-generated by the schema generator.
# Do not edit manually.

from ..utils.typings import ValidPhoneNumber
from ..types import SetPasswordAccountResult
from .base import ApiMethod

class SetPasswordAccount(ApiMethod[SetPasswordAccountResult]):
    """Submit the two-step verification password for an account being sold.

    Only valid while the account is awaiting a password. Each call consumes one attempt.
    On success the account is registered and enters the automated checking period, and
    the response describes that checking window.

    Raises:
        ChangedPassword: (400) The password is Changed. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds. Hint: {value[hint]}
        InvalidPassword: (400) The password is invalid. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds. Hint: {value[hint]}
        AttemptsExhausted: (403) No remaining attempts left
        InvalidSellerAccountOwner: (403) You are not the owner of this sold account
        ExpiredStat: (409) This operation cannot be performed because the stat has expired
        InvalidSellSessionStat: (409) Sell session is not in a valid stat to perform this operation
        UnknowError: (500) Unknow error occurred. Error: {context}
    """

    __returning__ = SetPasswordAccountResult
    __request_method__ = "POST"

    password: str
    """Two-step verification password for an account awaiting password confirmation."""

    phone_number: ValidPhoneNumber
    """Telegram account phone number in international E.164 format, including the leading '+'."""

__all__ = (
    "SetPasswordAccount", 
)
