# This file is auto-generated by the schema generator.
# Do not edit manually.

from typing import Optional

from ..utils.typings import ValidPhoneNumber, ValidTgOtpCode
from ..types import SetCodeAccountResult
from .base import ApiMethod

class SetCodeAccount(ApiMethod[SetCodeAccountResult]):
    """Submit the Telegram login code for an account being sold.

    Each call consumes one attempt. On success the account is registered and enters the
    automated checking period, and the response describes that checking window.

    If the account has two-step verification enabled the flow moves to the password stage
    instead: when `password` was supplied it is applied immediately and checking proceeds,
    otherwise the caller is told a password is required.

    Raises:
        ChangedPassword: (400) The password is Changed. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds. Hint: {value[hint]}
        ExpiredVerificationCode: (400) The verification code is expired. The operation was cancelled.
        InvalidPassword: (400) The password is invalid. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds. Hint: {value[hint]}
        InvalidPhoneNumber: (400) The phone_number is invalid. It may be prohibited, restricted, etc. The operation was cancelled.
        InvalidVerificationCode: (400) The verification code is invalid. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds
        SessionPasswordNeeded: (401) Two-step verification password is required to complete authentication for {value[account]}. Password hint: {value[hint]}. You have {value[attempts]} attempts remaining Within {value[seconds]} seconds
        AttemptsExhausted: (403) No remaining attempts left
        InvalidSellerAccountOwner: (403) You are not the owner of this sold account
        PhoneNumberUnoccupied: (404) The phone number is not registered on Telegram
        ExpiredStat: (409) This operation cannot be performed because the stat has expired
        InvalidSellSessionStat: (409) Sell session is not in a valid stat to perform this operation
        UnknowError: (500) Unknow error occurred. Error: {context}
    """

    __returning__ = SetCodeAccountResult
    __request_method__ = "POST"

    code: ValidTgOtpCode
    """Telegram login verification code. Embedded spaces are stripped before validation."""

    phone_number: ValidPhoneNumber
    """Telegram account phone number in international E.164 format, including the leading '+'."""

    password: Optional[str] = None
    """Two-step verification password, supplied upfront. When the account requires one, it is applied immediately instead of returning SESSION_PASSWORD_NEEDED."""

__all__ = (
    "SetCodeAccount", 
)
