"""Generate the enums / types / methods layer from the API schema.

Reads `compiler/schema/source.json` -- the API's JSON-Schema dump -- and emits
the three mirrored packages the SDK exposes, one symbol per module:

    WolfTg/enums/     a StrEnum per titled enum
    WolfTg/types/     an ApiObject per result shape, plus result type aliases
    WolfTg/methods/   an ApiMethod per API method

Every package is wiped at the start of a run except its hand-written `base.py`,
so a symbol dropped from the schema cannot linger as a stale file.

One module per *public* symbol. The anonymous objects nested inside a result
are written into whichever file uses them, repeated rather than shared, so no
two-field helper ends up in a module of its own.

An enum carrying a `title` becomes a named class in `WolfTg/enums/`; one
without stays inline as a `Literal`, since an untitled value set is just what
a single field accepts rather than a type in its own right.

Everything is derived from the schema. The one thing it cannot tell us is which
of its scalars map onto the SDK's own validated types, which is the
SCALAR_HINTS table in the CONFIGURATION block below. Everything after that
block is generic.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import ast
import json
import re
import shutil


_SNAKE1_PATTERN = re.compile(r"(.)([A-Z][a-z]+)")
_SNAKE2_PATTERN = re.compile(r"([a-z0-9])([A-Z])")
_STRING_PATTERN = re.compile(r"'[^']*'|\"[^\"]*\"")


# ===========================================================================
# CONFIGURATION
# ===========================================================================
# Everything the generator can be retargeted by lives here: where it reads and
# writes, the SDK names the generated code binds to, the naming rules, and the
# schema vocabulary it reads. Nothing below this block hardcodes any of them.
# ===========================================================================

# --- paths -----------------------------------------------------------------

BASE = Path(__file__).parent.parent.parent
SOURCE = BASE / "compiler/schema/source.json"
DEST = BASE / "WolfTg"

# --- generated layout ------------------------------------------------------

# The packages that get regenerated, and the one module in each that is
# hand-written and must survive the wipe.
PACKAGES = ("enums", "types", "methods")
KEPT_MODULE = "base"

# Which package each kind of generated symbol belongs to.
ENUM_PACKAGE = "enums"
TYPE_PACKAGE = "types"
METHOD_PACKAGE = "methods"

HEADER = """
# This file is auto-generated by the schema generator.
# Do not edit manually.
""".strip()

INDENT = "    "

ENCODING = "utf-8"
PY_EXT = ".py"
PYCACHE = "__pycache__"
INIT_MODULE = "__init__"

# --- SDK names the generated code binds to ---------------------------------

# Base classes, and the module each comes from relative to its own package.
MODEL_BASE = "ApiObject"
METHOD_BASE = "ApiMethod"
ENUM_BASE = "StrEnum"

BASE_MODULE = f".{KEPT_MODULE}"
COMPAT_MODULE = ".._compat"
TYPINGS_MODULE = "..utils.typings"
ENUM_STDLIB_MODULE = "enum"
ENUM_AUTO = "auto"

TYPING_MODULE = "typing"
PYDANTIC_MODULE = "pydantic"
FIELD_HELPER = "Field"

# The two class attributes every `ApiMethod` subclass declares.
RETURNING_ATTR = "__returning__"
REQUEST_METHOD_ATTR = "__request_method__"

# --- naming rules ----------------------------------------------------------

# `GetBalance` -> `GetBalanceResult`.
RESULT_SUFFIX = "Result"

# Marks a model that is nested inside a result rather than named by the API.
PRIVATE_PREFIX = "_"

# Appended when an anonymous model sits directly under `result`, with no
# property name of its own to borrow: `_AvailableCountriesResultItem`.
MAP_ITEM_SUFFIX = "item"

# A segment the compiler appends to a schema path as it descends into a map,
# marking a step with no property name of its own. It shows up in derived
# model names, so it reads as a word: `GetCountryInfo.result.buy_options.value`.
VALUE_SEGMENT = "value"

# (field name, JSON type) -> validated scalar from `WolfTg.utils.typings`.
# Keyed on the type too, because the same name means different things at
# different types: `code` is an OTP string on the way in but a plain int on
# the way out, and `country_code` is an ISO region in but a dialing prefix out.
SCALAR_HINTS: dict[tuple[str, str], str] = {
    ("phone_number", "string"): "ValidPhoneNumber",
    ("country_code", "string"): "ValidRegionCode",
    ("region_code", "string"): "ValidRegionCode",
    ("code", "string"): "ValidTgOtpCode",
}

# --- type expressions ------------------------------------------------------

# The `typing` names the generated annotations are built from.
DICT_TYPE = "Dict"
UNION_TYPE = "Union"
OPTIONAL_TYPE = "Optional"
ANY_TYPE = "Any"
NONE_TYPE = "None"

# What an enum the schema never titled compiles to, inline at the use site.
LITERAL_TYPE = "Literal"

# The one name for "an int or a float" -- the API spells amounts either way.
NUMBER_TYPE = "Number"

# Key type for an open-ended map the schema never describes.
DEFAULT_KEY_TYPE = "str"

# Imported from `typing`; everything else there is left alone.
TYPING_NAMES = frozenset((
    ANY_TYPE, DICT_TYPE, LITERAL_TYPE, OPTIONAL_TYPE, UNION_TYPE, "List", "Tuple",
))

# Imported from TYPINGS_MODULE. `Number` arrives there from `pytools.typings`,
# which `WolfTg.utils.typings` re-exports wholesale.
SCALAR_NAMES = frozenset(SCALAR_HINTS.values()) | {NUMBER_TYPE}

# Import blocks, in the order they are written out. Anything unlisted (a
# sibling module in the same package) sorts after these, alphabetically.
IMPORT_ORDER = (
    TYPING_MODULE,
    PYDANTIC_MODULE,
    ENUM_STDLIB_MODULE,
    COMPAT_MODULE,
    TYPINGS_MODULE,
    f"..{ENUM_PACKAGE}",
    f"..{TYPE_PACKAGE}",
)

# --- schema vocabulary -----------------------------------------------------

# Top-level shape of the source dump: named schemas endpoints are free to
# reference, and the endpoints themselves.
DEFS_KEY = "$defs"
ENDPOINTS_KEY = "endpoints"

# A `{"$ref": "#/$defs/AccountSection"}` node points at a $defs entry instead
# of repeating it. Compiling the pointed-to schema is what gives a titled enum
# the same class no matter how many places reference it.
REF_KEY = "$ref"
REF_PREFIX = f"#/{DEFS_KEY}/"

# Keys of one method entry in the source dump.
PATH_KEY = "path"
VERBS_KEY = "methods"
DESCRIPTION_KEY = "description"
REQUEST_KEY = "request"
RESPONSE_KEY = "response"
ERRORS_KEY = "errors"

# Where the payload sits inside the response envelope.
RESULT_KEY = "result"

# Custom extension documenting a map's shape in prose when `propertyNames`
# cannot express it.
VARIANTS_KEY = "x-variants"

# Standard JSON-Schema keywords. `title` on an enum node is what names the
# generated class; an enum without one stays inline as a `Literal`.
PROPERTIES_KEY = "properties"
REQUIRED_KEY = "required"
ENUM_KEY = "enum"
TITLE_KEY = "title"
ANY_OF_KEY = "anyOf"
CONST_KEY = "const"
TYPE_KEY = "type"
DEFAULT_KEY = "default"
ADDITIONAL_KEY = "additionalProperties"
PROPERTY_NAMES_KEY = "propertyNames"

# JSON-Schema type -> Python type.
PRIMITIVES: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}
NULL_TYPE = "null"
OBJECT_TYPE = "object"

# The pair the API uses to mean "a decimal amount", collapsed to NUMBER_TYPE.
NUMBER_UNION = frozenset(("integer", "number"))

# JSON-Schema validation keyword -> pydantic `Field` keyword.
CONSTRAINTS: dict[str, str] = {
    "exclusiveMinimum": "gt",
    "exclusiveMaximum": "lt",
    "minimum": "ge",
    "maximum": "le",
    "minLength": "min_length",
    "maxLength": "max_length",
    "pattern": "pattern",
}

# --- docstrings ------------------------------------------------------------

# The `Raises:` section listing the exceptions a method can raise. The class
# name is the error id in PascalCase, matching the error generator.
RAISES_HEADER = "Raises:"
RAISES_LINE = "{indent}{exception}: ({code}) {message}"


# ===========================================================================
# Rendering helpers
# ===========================================================================

REQUIRED = object()  # sentinel: field has no default


class Raw(str):
    """A default that is already Python source -- an enum member, say."""



def snake(text: str) -> str:
    return ("_" if text.startswith("_") else "") + _SNAKE2_PATTERN.sub(
        r"\1_\2", _SNAKE1_PATTERN.sub(r"\1_\2", text)
    ).lower()

def pascal(text: str) -> str:
    return "".join(i.capitalize() for i in snake(text).split("_") if i)

def literal(value: Any) -> str:
    return str(value) if isinstance(value, Raw) else repr(value)


def derive_model_name(path: str) -> str:
    """Name an anonymous nested object after where it sits.

    `GetCountryInfo.result.buy_options.value` -> `_GetCountryInfoBuyOptions`
    `AvailableCountries.result|1.value.value` -> `_AvailableCountriesResultItem`
    """

    method, *rest = [re.sub(r"\|\d+$", "", part) for part in path.split(".")]

    # Trailing map-value hops mean "the thing inside this map" -- they carry no
    # name of their own, so drop them and remember we went through a map.
    mapped = False

    while rest and rest[-1] == VALUE_SEGMENT:
        rest.pop()
        mapped = True

    # Every response path starts at `result`, which only earns a place in the
    # name when nothing more specific followed it.
    if len(rest) > 1 and rest[0] == RESULT_KEY:
        rest.pop(0)

    if mapped and rest == [RESULT_KEY]:
        rest.append(MAP_ITEM_SUFFIX)

    return PRIVATE_PREFIX + method + "".join(pascal(part) for part in rest)


def map_key_names(text: str) -> list[str]:
    """Key names from the `{section: {country_code: price}}` prose notation.

    The schema documents the keys of an open-ended map in `x-variants` rather
    than in `propertyNames`, outermost first. Reading them back is what lets a
    country-keyed map land on `RegionCode` instead of a bare `str`.
    """

    return list(dict.fromkeys(re.findall(r"\{(\w+):", text)))


def tokens(expr: str) -> list[str]:
    """The identifiers inside a rendered type expression.

    Quoted text is blanked first: the members of a `Literal['buy', 'sell']`
    are data, and must not be mistaken for symbols needing an import.
    """

    return re.findall(r"[A-Za-z_][A-Za-z0-9_]*", _STRING_PATTERN.sub(" ", expr))


def docstring(text: str, indent: str) -> str:
    """Render `text` as a docstring, escaping anything that would break out."""

    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = body.split("\n")

    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""'

    out = [f'{indent}"""{lines[0]}']
    out += [f"{indent}{line}".rstrip() for line in lines[1:]]
    out.append(f'{indent}"""')
    return "\n".join(out)


def render_all(names: list[str]) -> str:
    body = "".join(f'    "{name}", \n' for name in names)
    return f"__all__ = (\n{body})"


def base_exports(package: str) -> list[str]:
    """The `__all__` of a package's hand-written kept module, read not assumed."""

    path = DEST / package / f"{KEPT_MODULE}{PY_EXT}"

    if not path.exists():
        return []

    for node in ast.walk(ast.parse(path.read_text(encoding=ENCODING))):
        if not isinstance(node, ast.Assign):
            continue
        if not any(getattr(t, "id", None) == "__all__" for t in node.targets):
            continue

        return [e.value for e in node.value.elts if isinstance(e, ast.Constant)]

    return []


def render_fields(fields: list["ModelField"], imports: "Imports") -> str:
    """Render a field block, spacing out only the ones carrying a docstring.

    Bare `name: type` lines read better packed together; a documented field
    needs air around it so its docstring cannot be mistaken for belonging to
    the field below.
    """

    out = []

    for i, f in enumerate(fields):
        if i and (f.doc or fields[i - 1].doc):
            out.append("")

        out.append(f.render(imports))

    return "\n".join(out)


# ===========================================================================
# Imports
# ===========================================================================

class Imports:
    """Resolves symbols to import lines for one generated module.

    A symbol defined in the same package is imported from its own module
    rather than through the package `__init__`, so the generated modules do
    not depend on their package being fully initialised first.
    """

    def __init__(self, table: dict[str, tuple[str, str]], package: str) -> None:
        self.table = table
        self.package = package
        self._by_module: dict[str, set[str]] = {}

    def add(self, module: str, name: str) -> str:
        self._by_module.setdefault(module, set()).add(name)
        return name

    def use(self, symbol: str) -> None:
        """Import `symbol` from wherever it is defined, if it needs importing."""

        if symbol in TYPING_NAMES:
            self.add(TYPING_MODULE, symbol)

        elif symbol in SCALAR_NAMES:
            self.add(TYPINGS_MODULE, symbol)

        elif (location := self.table.get(symbol)) is not None:
            package, module = location
            self.add(f".{module}" if package == self.package else f"..{package}", symbol)

    def use_expr(self, expr: str) -> None:
        for symbol in tokens(expr):
            self.use(symbol)

    def render(self) -> str:
        ranked = sorted(
            self._by_module.items(),
            key=lambda item: (
                IMPORT_ORDER.index(item[0]) if item[0] in IMPORT_ORDER else len(IMPORT_ORDER),
                item[0],
            ),
        )
        lines = [f"from {module} import {', '.join(sorted(names))}" for module, names in ranked]

        external = [line for line in lines if not line.startswith("from .")]
        local = [line for line in lines if line.startswith("from .")]

        return "\n\n".join(filter(None, ["\n".join(external), "\n".join(local)]))


# ===========================================================================
# Units -- one generated module each
# ===========================================================================

@dataclass
class ModelField:
    name: str
    type_expr: str
    default: Any = REQUIRED
    constraints: dict[str, Any] = field(default_factory=dict)
    doc: Optional[str] = None


    @property
    def signature(self) -> tuple:
        default = literal(self.default) if self.default is not REQUIRED else None
        return (self.name, self.type_expr, default)

    def render(self, imports: Imports) -> str:
        imports.use_expr(self.type_expr)
        line = f"{INDENT}{self.name}: {self.type_expr}"

        if self.constraints:
            imports.add(PYDANTIC_MODULE, FIELD_HELPER)
            args = [literal(self.default)] if self.default is not REQUIRED else []
            args += [f"{CONSTRAINTS[k]}={literal(v)}" for k, v in sorted(self.constraints.items())]
            line += f" = {FIELD_HELPER}({', '.join(args)})"

        elif self.default is not REQUIRED:
            imports.use_expr(literal(self.default))
            line += f" = {literal(self.default)}"

        if self.doc:
            line += "\n" + docstring(self.doc, INDENT)

        return line


@dataclass
class Enum:
    name: str
    values: list[str]
    inline: tuple = ()

    package = ENUM_PACKAGE

    @property
    def module(self) -> str:
        return snake(self.name)

    def render(self, imports: Imports) -> str:
        imports.add(ENUM_STDLIB_MODULE, ENUM_AUTO)
        imports.add(COMPAT_MODULE, ENUM_BASE)

        members = "\n".join(f"{INDENT}{value.upper()} = {ENUM_AUTO}()" for value in self.values)
        return f"class {self.name}({ENUM_BASE}):\n{members}"


@dataclass
class Model:
    name: str
    fields: list[ModelField]
    base: str = MODEL_BASE
    inherited: list[ModelField] = field(default_factory=list)

    # Anonymous models this one is built out of. They are written into the
    # same file rather than getting one of their own -- see `emit_unit`.
    inline: list["Model"] = field(default_factory=list)

    package = TYPE_PACKAGE

    @property
    def module(self) -> str:
        return snake(self.name)

    @property
    def signature(self) -> tuple:
        return tuple(f.signature for f in self.inherited + self.fields)

    def render(self, imports: Imports) -> str:
        if self.base == MODEL_BASE:
            imports.add(BASE_MODULE, MODEL_BASE)
        else:
            imports.use(self.base)

        body = render_fields(self.fields, imports) or f"{INDENT}pass"
        return f"class {self.name}({self.base}):\n{body}"


@dataclass
class Alias:
    """A result that is a bare container rather than an object."""

    name: str
    expr: str
    doc: Optional[str] = None
    inline: list[Model] = field(default_factory=list)

    package = TYPE_PACKAGE

    @property
    def module(self) -> str:
        return snake(self.name)

    def render(self, imports: Imports) -> str:
        imports.use_expr(self.expr)
        line = f"{self.name} = {self.expr}"

        if not self.doc:
            return line

        # A comment, not a docstring: PEP 224 attribute docs do not attach to
        # a module-level type alias, so a docstring here would be a stray
        # expression statement.
        comment = "\n".join(f"# {part}".rstrip() for part in self.doc.split("\n"))
        return f"{comment}\n{line}"


@dataclass
class Method:
    name: str
    verb: str
    returning: str
    description: str
    fields: list[ModelField]
    errors: dict[str, dict[str, str]] = field(default_factory=dict)
    inline: list[Model] = field(default_factory=list)

    package = METHOD_PACKAGE

    @property
    def module(self) -> str:
        return snake(self.name)

    def raises(self) -> str:
        """The `Raises:` section, naming the exception class per error id.

        The class names follow the same SCREAMING_SNAKE -> PascalCase rule the
        error generator uses, so every name here resolves to a real class in
        `WolfTg.errors`.
        """

        if not self.errors:
            return ""

        lines = [RAISES_HEADER]

        for code in sorted(self.errors, key=int):
            for error_id, message in sorted(self.errors[code].items()):
                lines.append(RAISES_LINE.format(
                    indent=INDENT, exception=pascal(error_id), code=code, message=message,
                ))

        return "\n".join(lines)

    def render(self, imports: Imports) -> str:
        imports.add(BASE_MODULE, METHOD_BASE)
        imports.use(self.returning)

        text = "\n\n".join(filter(None, [self.description, self.raises()]))

        head = f"class {self.name}({METHOD_BASE}[{self.returning}]):"
        doc = docstring(text, INDENT) if text else ""
        attrs = (
            f"{INDENT}{RETURNING_ATTR} = {self.returning}\n"
            f'{INDENT}{REQUEST_METHOD_ATTR} = "{self.verb}"'
        )

        return "\n\n".join(filter(None, [
            head + ("\n" + doc if doc else ""),
            attrs,
            render_fields(self.fields, imports),
        ]))


# ===========================================================================
# Registry
# ===========================================================================

class Registry:
    """Every symbol emitted, de-duplicated."""

    def __init__(self) -> None:
        self.enums: dict[str, Enum] = {}
        self.models: list[Model] = []
        self.aliases: list[Alias] = []
        self.methods: list[Method] = []
        self._by_signature: dict[tuple, Model] = {}

    @property
    def units(self) -> list:
        return [*self.enums.values(), *self.models, *self.aliases, *self.methods]

    @property
    def enum_members(self) -> dict[str, list[str]]:
        return {e.name: e.values for e in self.enums.values()}

    def symbol_table(self) -> dict[str, tuple[str, str]]:
        table = {u.name: (u.package, u.module) for u in self.units}

        # Whatever the hand-written kept module of each package exports.
        for package in PACKAGES:
            for name in base_exports(package):
                table[name] = (package, KEPT_MODULE)

        return table

    # --- enums ---

    def enum(self, name: str, values: list[str], path: str) -> str:
        """Register the enum class the schema titled `name`.

        The same title is expected to carry the same members everywhere it
        appears; if it does not, the first one wins and the clash is reported
        rather than silently resolved.
        """

        if (existing := self.enums.get(name)) is not None:
            if existing.values != values:
                print(f"  ! {name} at {path} has different members; keeping the first")

            return name

        self.enums[name] = Enum(name, values)
        return name

    # --- models ---

    def model(self, name: str, fields: list[ModelField], inline: list[Model]) -> str:
        """Register a public result model, folding it into an existing one.

        An exact structural match is subclassed with an empty body -- the name
        is public API, so it has to stay even when the shape is a repeat.
        Otherwise the largest existing model whose fields are a leading subset
        becomes the base, and only the remaining fields are emitted.

        Only public models take part: the anonymous ones live inside whichever
        file uses them, where a base from another module would not be in scope.
        """

        signature = tuple(f.signature for f in fields)

        if (twin := self._by_signature.get(signature)) is not None:
            self.models.append(Model(name, [], base=twin.name, inherited=list(fields)))
            return name

        base, inherited = self._best_base(fields)
        model = Model(name, fields[len(inherited):], base=base, inherited=inherited, inline=inline)

        self.models.append(model)
        self._by_signature[signature] = model
        return name

    def _best_base(self, fields: list[ModelField]) -> tuple[str, list[ModelField]]:
        best: Optional[Model] = None

        for candidate in self.models:
            depth = len(candidate.signature)

            if not 0 < depth < len(fields):
                continue
            if candidate.signature != tuple(f.signature for f in fields[:depth]):
                continue
            if best is None or depth > len(best.signature):
                best = candidate

        if best is None:
            return MODEL_BASE, []

        return best.name, fields[:len(best.signature)]


# ===========================================================================
# JSON Schema -> Python type expressions
# ===========================================================================

class TypeCompiler:
    """Turns schema nodes into type expressions, registering what they need.

    Only produces source text -- imports are resolved later, once every symbol
    has a home, by tokenizing the expressions this returns.

    Anonymous nested objects are collected in `_inline` as they are met, and
    handed to whichever unit is being built via `take_inline()`. Two units
    needing the same shape each get their own copy, which keeps every
    generated file readable on its own.

    `defs` is the schema's `$defs` table -- every named, reusable shape a
    `$ref` can point at. Resolving a ref just compiles the pointed-to schema,
    so a `$ref`'d enum goes through the same titled/untitled rule as one
    written out in place, and de-dupes against it the same way.
    """

    def __init__(self, registry: Registry, defs: dict[str, dict]) -> None:
        self.registry = registry
        self.defs = defs
        self._inline: list[Model] = []

    def take_inline(self) -> list[Model]:
        """The anonymous models met since the last call, innermost first."""

        collected, self._inline = self._inline, []
        return collected

    def compile(self, schema: dict, path: str, name: str = "", keys: tuple = (), depth: int = 0) -> str:
        """`path` locates the node, `name` is the property it was reached
        through (for the scalar hints), and `keys`/`depth` carry the map key
        names documented in an enclosing `x-variants`."""

        # A node documenting its own map shape restarts the key trail.
        if variants := schema.get(VARIANTS_KEY):
            if found := map_key_names(variants):
                keys, depth = tuple(found), 0

        if REF_KEY in schema:
            return self._ref(schema[REF_KEY])

        if ENUM_KEY in schema:
            return self._enum(schema, path)

        if ANY_OF_KEY in schema:
            return self._any_of(schema[ANY_OF_KEY], path, name, keys, depth)

        if CONST_KEY in schema:
            return self._const(schema[CONST_KEY])

        kind = schema.get(TYPE_KEY)

        if kind == OBJECT_TYPE:
            return self._object(schema, path, name, keys, depth)

        if kind == NULL_TYPE:
            return NONE_TYPE

        if kind in PRIMITIVES:
            return SCALAR_HINTS.get((name, kind)) or PRIMITIVES[kind]

        return ANY_TYPE

    # --- branches ---

    def _ref(self, ref: str) -> str:
        def_name = ref.removeprefix(REF_PREFIX)
        return self.compile(self.defs[def_name], f"{DEFS_KEY}.{def_name}", def_name)

    def _enum(self, schema: dict, path: str) -> str:
        """A titled enum becomes a class; an untitled one stays a `Literal`.

        The title is the schema saying "this value set is a thing with a name
        and a life of its own". Without one, the members are just the values
        this one field accepts, and inlining them keeps a single-use set from
        becoming a public class nobody asked for.
        """

        values = schema[ENUM_KEY]

        if title := schema.get(TITLE_KEY):
            return self.registry.enum(title, values, path)

        return f"{LITERAL_TYPE}[{', '.join(repr(v) for v in values)}]"

    def _const(self, value: Any) -> str:
        kind = {bool: "boolean", int: "integer", float: "number", str: "string"}.get(type(value))
        return PRIMITIVES[kind] if kind else ANY_TYPE

    def _any_of(self, members: list[dict], path: str, name: str, keys: tuple, depth: int) -> str:
        nullable = any(m.get(TYPE_KEY) == NULL_TYPE for m in members)
        real = [m for m in members if m.get(TYPE_KEY) != NULL_TYPE]

        # `int | float` is the API's way of spelling "a decimal amount"; the
        # SDK has one name for that.
        if {m.get(TYPE_KEY) for m in real} == set(NUMBER_UNION):
            exprs = [NUMBER_TYPE]
        else:
            # Alternatives sit side by side, so they all start at this depth.
            exprs = [self.compile(m, f"{path}|{i}", name, keys, depth) for i, m in enumerate(real)]

        exprs = list(dict.fromkeys(exprs))
        expr = self._merge_maps(exprs) if len(exprs) > 1 else exprs[0]

        return f"{OPTIONAL_TYPE}[{expr}]" if nullable else expr

    def _merge_maps(self, exprs: list[str]) -> str:
        """Union alternatives, factoring a shared `Dict[K, ...]` prefix inward.

        `Dict[K, A] | Dict[K, B]` is really "a map of K to either" -- saying it
        that way keeps the alternation on the leaf, where it belongs.
        """

        prefixes = {e.split(", ", 1)[0] for e in exprs}

        if len(prefixes) == 1 and all(e.startswith(f"{DICT_TYPE}[") for e in exprs):
            prefix = prefixes.pop()
            values = [e[len(prefix) + 2:-1] for e in exprs]
            return f"{prefix}, {self._merge_maps(values) if len(set(values)) > 1 else values[0]}]"

        return f"{UNION_TYPE}[{', '.join(exprs)}]"

    def _object(self, schema: dict, path: str, name: str, keys: tuple, depth: int) -> str:
        if PROPERTIES_KEY in schema:
            return self._inline_model(schema, path)

        value_schema = schema.get(ADDITIONAL_KEY)

        if not isinstance(value_schema, dict):
            return f"{DICT_TYPE}[{DEFAULT_KEY_TYPE}, {ANY_TYPE}]"

        # `propertyNames` states the key set outright (inline or via `$ref`);
        # failing that, fall back to the name the prose gave this depth, run
        # through the scalar hints.
        if names := schema.get(PROPERTY_NAMES_KEY):
            key = self.compile(names, f"{path}.{PROPERTY_NAMES_KEY}")
        else:
            documented = keys[depth] if depth < len(keys) else ""
            key = SCALAR_HINTS.get((documented, "string"), DEFAULT_KEY_TYPE)

        value = self.compile(value_schema, f"{path}.{VALUE_SEGMENT}", name, keys, depth + 1)
        return f"{DICT_TYPE}[{key}, {value}]"

    # --- model building ---

    def fields(self, schema: dict, path: str) -> list[ModelField]:
        required = set(schema.get(REQUIRED_KEY, ()))
        fields = [
            self.field(prop, prop_schema, self.compile(prop_schema, f"{path}.{prop}", prop), prop in required)
            for prop, prop_schema in schema.get(PROPERTIES_KEY, {}).items()
        ]

        # Required first: the schema mostly orders them that way already, and
        # pydantic does not care, but it reads better and keeps diffs stable.
        fields.sort(key=lambda f: f.default is not REQUIRED)
        return fields

    def model(self, schema: dict, path: str, name: str) -> str:
        """Build a public result model, taking any anonymous models with it."""

        fields = self.fields(schema, path)
        return self.registry.model(name, fields, self.take_inline())

    def _inline_model(self, schema: dict, path: str) -> str:
        """Build an anonymous model, to be written into the caller's file.

        Reused within the unit being built, duplicated across units -- the
        alternative is a shared module per shape, which buries a two-field
        helper in a file of its own.
        """

        fields = self.fields(schema, path)
        signature = tuple(f.signature for f in fields)

        for existing in self._inline:
            if existing.signature == signature:
                return existing.name

        self._inline.append(model := Model(derive_model_name(path), fields))
        return model.name

    def field(self, name: str, schema: dict, type_expr: str, required: bool) -> ModelField:
        constraints = {k: v for k, v in schema.items() if k in CONSTRAINTS}
        doc = schema.get(DESCRIPTION_KEY)

        if required:
            return ModelField(name, type_expr, REQUIRED, constraints, doc)

        default = schema.get(DEFAULT_KEY)

        # A null default only makes sense on an optional type; the schema
        # usually spells that out via `anyOf`, but not always.
        if default is None and not type_expr.startswith(f"{OPTIONAL_TYPE}["):
            type_expr = f"{OPTIONAL_TYPE}[{type_expr}]"

        # An enum's default is a wire value; name the member instead.
        elif type_expr in self.registry.enum_members:
            default = Raw(f"{type_expr}.{str(default).upper()}")

        return ModelField(name, type_expr, default, constraints, doc)


# ===========================================================================
# Emitters
# ===========================================================================

def reset(package: str) -> None:
    """Clear a package of everything it did not write by hand."""

    folder = DEST / package
    folder.mkdir(parents=True, exist_ok=True)

    for path in folder.glob(f"*{PY_EXT}"):
        if path.stem != KEPT_MODULE:
            path.unlink()

    shutil.rmtree(folder / PYCACHE, ignore_errors=True)


def write(relative: str, *blocks: str) -> None:
    text = "\n\n".join(b for b in blocks if b).strip() + "\n"
    (DEST / relative).write_text(text, encoding=ENCODING)


def emit_unit(unit, table: dict[str, tuple[str, str]]) -> None:
    imports = Imports(table, unit.package)

    # Rendering is what discovers the imports, so it has to come first. The
    # anonymous models go above the unit that uses them, innermost first.
    bodies = [model.render(imports) for model in unit.inline]
    bodies.append(unit.render(imports))

    write(
        f"{unit.package}/{unit.module}{PY_EXT}",
        HEADER,
        imports.render(),
        "\n\n".join(bodies),
        render_all([unit.name]),
    )


def emit_init(package: str, modules: list[str], exported: list[str]) -> None:
    """Re-export the package's public surface.

    Every module is star-imported so its symbol lands in the package
    namespace, but `__all__` lists only the public names: the anonymous nested
    models stay reachable for anyone who needs them without becoming part of
    `from WolfTg.types import *`.
    """

    write(
        f"{package}/{INIT_MODULE}{PY_EXT}",
        HEADER,
        "\n".join(f"from .{m} import *" for m in sorted(modules)),
        render_all(sorted(exported)),
    )


# ===========================================================================
# Driver
# ===========================================================================

def build(source: dict) -> Registry:
    registry = Registry()
    compiler = TypeCompiler(registry, source.get(DEFS_KEY, {}))

    for name, spec in source[ENDPOINTS_KEY].items():
        result_schema = spec[RESPONSE_KEY][PROPERTIES_KEY][RESULT_KEY]
        result_path = f"{name}.{RESULT_KEY}"

        # Every method gets its own `{Method}Result`, even where two methods
        # return the same shape -- the repeat is emitted as an empty subclass,
        # so both names exist and neither shape is written twice.
        returning = f"{name}{RESULT_SUFFIX}"

        if PROPERTIES_KEY in result_schema:
            compiler.model(result_schema, result_path, returning)

        else:
            # A bare container (a map of maps) is a type alias, not a class.
            expr = compiler.compile(result_schema, result_path, RESULT_KEY)
            registry.aliases.append(Alias(
                returning, expr, result_schema.get(VARIANTS_KEY), compiler.take_inline(),
            ))

        request = spec.get(REQUEST_KEY) or {}
        fields = compiler.fields(request, f"{name}.{REQUEST_KEY}")

        registry.methods.append(Method(
            name=name,
            verb=spec[VERBS_KEY][0],
            returning=returning,
            description=spec.get(DESCRIPTION_KEY, ""),
            fields=fields,
            errors=spec.get(ERRORS_KEY) or {},
            inline=compiler.take_inline(),
        ))

    return registry


def start() -> None:
    source: dict = json.loads(SOURCE.read_text(encoding=ENCODING))

    print(f"compiling {len(source[ENDPOINTS_KEY])} methods from {SOURCE.name}")

    registry = build(source)
    table = registry.symbol_table()

    for package in PACKAGES:
        reset(package)

    for unit in registry.units:
        emit_unit(unit, table)

    for package in PACKAGES:
        units = [u for u in registry.units if u.package == package]

        # Each package keeps a hand-written module; only enums has none.
        kept = base_exports(package)
        modules = [u.module for u in units] + ([KEPT_MODULE] if kept else [])
        exported = [u.name for u in units if not u.name.startswith(PRIVATE_PREFIX)] + kept

        emit_init(package, modules, exported)
        print(f"  + {DEST.name}/{package}/ ({len(modules)} modules, {len(exported)} exported)")

    print(
        f"done: {len(registry.enums)} enums, {len(registry.models)} models, "
        f"{len(registry.aliases)} aliases, {len(registry.methods)} methods"
    )


if __name__ == "__main__":
    start()
