# This file is auto-generated by the error generator.
# Do not edit manually.

count = 36

exceptions = {
    400: {
        "_": "BadRequest", 
        "CHANGED_PASSWORD": "ChangedPassword", 
        "EXPIRED_VERIFICATION_CODE": "ExpiredVerificationCode", 
        "INVALID_CONTENT_TYPE": "InvalidContentType", 
        "INVALID_PASSWORD": "InvalidPassword", 
        "INVALID_PHONE_NUMBER": "InvalidPhoneNumber", 
        "INVALID_USER_ID": "InvalidUserId", 
        "INVALID_VERIFICATION_CODE": "InvalidVerificationCode", 
    }, 
    401: {
        "_": "Unauthorized", 
        "MISSING_AUTHENTICATION_HEADERS": "MissingAuthenticationHeaders", 
        "ORDER_ACCESS_DENIED": "OrderAccessDenied", 
        "SESSION_PASSWORD_NEEDED": "SessionPasswordNeeded", 
        "USER_API_KEY_NOT_FOUND": "UserApiKeyNotFound", 
        "USER_API_KEY_REVOKED": "UserApiKeyRevoked", 
    }, 
    403: {
        "_": "Forbidden", 
        "ATTEMPTS_EXHAUSTED": "AttemptsExhausted", 
        "INVALID_BUYER_ACCOUNT_OWNER": "InvalidBuyerAccountOwner", 
        "INVALID_SELLER_ACCOUNT_OWNER": "InvalidSellerAccountOwner", 
        "NUMBER_BLOCKED_FROM_SELL": "NumberBlockedFromSell", 
        "USER_BANNED_FROM_API": "UserBannedFromApi", 
        "USER_BANNED_FROM_BUYING": "UserBannedFromBuying", 
        "USER_BANNED_FROM_SELLING": "UserBannedFromSelling", 
    }, 
    404: {
        "_": "NotFound", 
        "NOT_FOUND_OTP_CODE": "NotFoundOtpCode", 
        "ORDER_NOT_FOUND": "OrderNotFound", 
        "PHONE_NUMBER_UNOCCUPIED": "PhoneNumberUnoccupied", 
    }, 
    405: {
        "_": "MethodNotAllowed", 
    }, 
    409: {
        "_": "Conflict", 
        "ACCOUNT_DEAD_DURING_GET_CODE": "AccountDeadDuringGetCode", 
        "ACCOUNT_FOR_BUY_SECTION_CLOSED": "AccountForBuySectionClosed", 
        "ACCOUNT_FOR_SELL_SECTION_CLOSED": "AccountForSellSectionClosed", 
        "ACCOUNT_PURCHASE_ATTEMPTS_EXHAUSTED": "AccountPurchaseAttemptsExhausted", 
        "EXPIRED_STAT": "ExpiredStat", 
        "INSUFFICIENT_BALANCE": "InsufficientBalance", 
        "INVALID_SELL_SESSION_STAT": "InvalidSellSessionStat", 
        "NO_ACCOUNTS_AVAILABLE_FOR_COUNTRY": "NoAccountsAvailableForCountry", 
        "SELL_ACCOUNT_STAT_ALREADY_EXISTS": "SellAccountStatAlreadyExists", 
        "SESSION_ALREADY_EXISTS": "SessionAlreadyExists", 
    }, 
    420: {
        "_": "Flood", 
        "TOO_MANY_REQUESTS": "TooManyRequests", 
    }, 
    500: {
        "_": "InternalServerError", 
        "TELEGRAM_ERROR": "TelegramError", 
        "UNKNOW_ERROR": "UnknowError", 
    }, 
    503: {
        "_": "ServiceUnavailable", 
        "API_UNAVAILABLE": "ApiUnavailable", 
    }, 
}

