# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class BadRequest(ApiError):
    """BadRequest"""
    CODE = 400
    """``int``: Error Code"""
    NAME = __doc__

class InvalidVerificationCode(BadRequest):
    """The verification code is invalid. You have {value[0]} attempts remaining Within {value[1]} seconds"""
    ID = "INVALID_VERIFICATION_CODE"
    """``str``: Error ID"""
    MESSAGE = __doc__

class ExpiredVerificationCode(BadRequest):
    """The verification code is expired. The operation was cancelled."""
    ID = "EXPIRED_VERIFICATION_CODE"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidPhoneNumber(BadRequest):
    """The phone_number is invalid. It may be prohibited, restricted, etc. The operation was cancelled."""
    ID = "INVALID_PHONE_NUMBER"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidPassword(BadRequest):
    """The password is invalid. You have {value[0]} attempts remaining Within {value[1]} seconds. Hint: {value[2]}"""
    ID = "INVALID_PASSWORD"
    """``str``: Error ID"""
    MESSAGE = __doc__

class ChangedPassword(BadRequest):
    """The password is Changed. You have {value[0]} attempts remaining Within {value[1]} seconds. Hint: {value[2]}"""
    ID = "CHANGED_PASSWORD"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidContentType(BadRequest):
    """Content-Type must be application/json"""
    ID = "INVALID_CONTENT_TYPE"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidUserId(BadRequest):
    """User id is invalid"""
    ID = "INVALID_USER_ID"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidSection(BadRequest):
    """Section is invalid"""
    ID = "INVALID_SECTION"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "InvalidVerificationCode", 
    "ExpiredVerificationCode", 
    "InvalidPhoneNumber", 
    "InvalidPassword", 
    "ChangedPassword", 
    "InvalidContentType", 
    "InvalidUserId", 
    "InvalidSection", 
)

