# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class Conflict(ApiError):
    """Conflict"""
    CODE = 409
    """``int``: Error Code"""
    NAME = __doc__

class InvalidSellSessionStat(Conflict):
    """Sell session is not in a valid stat to perform this operation"""
    ID = "INVALID_SELL_SESSION_STAT"
    """``str``: Error ID"""
    MESSAGE = __doc__

class ExpiredStat(Conflict):
    """This operation cannot be performed because the stat has expired"""
    ID = "EXPIRED_STAT"
    """``str``: Error ID"""
    MESSAGE = __doc__

class AccountForSellSectionClosed(Conflict):
    """Selling is not allowed for {value[0]} {value[1]} account section at the moment"""
    ID = "ACCOUNT_FOR_SELL_SECTION_CLOSED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class AccountForBuySectionClosed(Conflict):
    """Buying is not allowed for {value[0]} {value[1]} account section at the moment"""
    ID = "ACCOUNT_FOR_BUY_SECTION_CLOSED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class SessionAlreadyExists(Conflict):
    """A session already exists for this phone number"""
    ID = "SESSION_ALREADY_EXISTS"
    """``str``: Error ID"""
    MESSAGE = __doc__

class SellAccountStatAlreadyExists(Conflict):
    """A sell process already exists for this account"""
    ID = "SELL_ACCOUNT_STAT_ALREADY_EXISTS"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InsufficientBalance(Conflict):
    """You are does not have enough balance for this operation"""
    ID = "INSUFFICIENT_BALANCE"
    """``str``: Error ID"""
    MESSAGE = __doc__

class NoAccountsAvailableForCountry(Conflict):
    """No accounts available for purchase in this country"""
    ID = "NO_ACCOUNTS_AVAILABLE_FOR_COUNTRY"
    """``str``: Error ID"""
    MESSAGE = __doc__

class AccountPurchaseAttemptsExhausted(Conflict):
    """All purchase attempts have been exhausted without acquiring an account"""
    ID = "ACCOUNT_PURCHASE_ATTEMPTS_EXHAUSTED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class AccountDeadDuringGetCode(Conflict):
    """Account became dead during code retrieval process"""
    ID = "ACCOUNT_DEAD_DURING_GET_CODE"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "InvalidSellSessionStat", 
    "ExpiredStat", 
    "AccountForSellSectionClosed", 
    "AccountForBuySectionClosed", 
    "SessionAlreadyExists", 
    "SellAccountStatAlreadyExists", 
    "InsufficientBalance", 
    "NoAccountsAvailableForCountry", 
    "AccountPurchaseAttemptsExhausted", 
    "AccountDeadDuringGetCode", 
)

