# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class Flood(ApiError):
    """Flood"""
    CODE = 420
    """``int``: Error Code"""
    NAME = __doc__

class TooManyRequests(Flood):
    """Too many requests. Please try again after {value}s."""
    ID = "TOO_MANY_REQUESTS"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "Flood", 
    "TooManyRequests", 
)

