# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class Forbidden(ApiError):
    """Forbidden"""
    CODE = 403
    """``int``: Error Code"""
    NAME = __doc__

class AttemptsExhausted(Forbidden):
    """No remaining attempts left"""
    ID = "ATTEMPTS_EXHAUSTED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidBuyerAccountOwner(Forbidden):
    """You are not the owner of this buy account"""
    ID = "INVALID_BUYER_ACCOUNT_OWNER"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidSellerAccountOwner(Forbidden):
    """You are not the owner of this sold account"""
    ID = "INVALID_SELLER_ACCOUNT_OWNER"
    """``str``: Error ID"""
    MESSAGE = __doc__

class NumberBlockedFromSell(Forbidden):
    """This phone number is blocked from selling. Reason: {value}"""
    ID = "NUMBER_BLOCKED_FROM_SELL"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserBannedFromApi(Forbidden):
    """You are banned from using the API. Ban duration: {value}s"""
    ID = "USER_BANNED_FROM_API"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserBannedFromBuying(Forbidden):
    """You are banned from buying accounts. Ban duration: {value}s"""
    ID = "USER_BANNED_FROM_BUYING"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserBannedFromSelling(Forbidden):
    """You are banned from selling accounts. Ban duration: {value}s"""
    ID = "USER_BANNED_FROM_SELLING"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "Forbidden", 
    "AttemptsExhausted", 
    "InvalidBuyerAccountOwner", 
    "InvalidSellerAccountOwner", 
    "NumberBlockedFromSell", 
    "UserBannedFromApi", 
    "UserBannedFromBuying", 
    "UserBannedFromSelling", 
)

