# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class InternalServerError(ApiError):
    """InternalServerError"""
    CODE = 500
    """``int``: Error Code"""
    NAME = __doc__

class TelegramError(InternalServerError):
    """Unknow Telegram service error occurred. Error: {context}"""
    ID = "TELEGRAM_ERROR"
    """``str``: Error ID"""
    MESSAGE = __doc__
    STORE_VALUE = False

class UnknowError(InternalServerError):
    """Unknow error occurred. Error: {context}"""
    ID = "UNKNOW_ERROR"
    """``str``: Error ID"""
    MESSAGE = __doc__
    STORE_VALUE = False



__all__ = (
    "TelegramError", 
    "UnknowError", 
)

