# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class MethodNotAllowed(ApiError):
    """MethodNotAllowed"""
    CODE = 405
    """``int``: Error Code"""
    NAME = __doc__



__all__ = (
)

