# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class NotFound(ApiError):
    """NotFound"""
    CODE = 404
    """``int``: Error Code"""
    NAME = __doc__

class NotFoundOtpCode(NotFound):
    """OTP code is not available for this session at the moment"""
    ID = "NOT_FOUND_OTP_CODE"
    """``str``: Error ID"""
    MESSAGE = __doc__

class OrderNotFound(NotFound):
    """Order {value} not found"""
    ID = "ORDER_NOT_FOUND"
    """``str``: Error ID"""
    MESSAGE = __doc__

class PhoneNumberUnoccupied(NotFound):
    """The phone number is not registered on Telegram"""
    ID = "PHONE_NUMBER_UNOCCUPIED"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "NotFound", 
    "NotFoundOtpCode", 
    "OrderNotFound", 
    "PhoneNumberUnoccupied", 
)

