# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class ServiceUnavailable(ApiError):
    """ServiceUnavailable"""
    CODE = 503
    """``int``: Error Code"""
    NAME = __doc__

class ApiUnavailable(ServiceUnavailable):
    """The API is currently unavailable"""
    ID = "API_UNAVAILABLE"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "ApiUnavailable", 
)

