# This file is auto-generated by the error generator.
# Do not edit manually.

from ..api_error import ApiError

class Unauthorized(ApiError):
    """Unauthorized"""
    CODE = 401
    """``int``: Error Code"""
    NAME = __doc__

class SessionPasswordNeeded(Unauthorized):
    """Two-step verification password is required to complete authentication for {value[0]}. password hint: {value[1]}. You have {value[2]} attempts remaining Within {value[3]} seconds"""
    ID = "SESSION_PASSWORD_NEEDED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserApiKeyInvalid(Unauthorized):
    """Api key is invalid"""
    ID = "USER_API_KEY_INVALID"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserApiKeyNotFound(Unauthorized):
    """Api key not found"""
    ID = "USER_API_KEY_NOT_FOUND"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserApiKeyRevoked(Unauthorized):
    """Api key has been revoked"""
    ID = "USER_API_KEY_REVOKED"
    """``str``: Error ID"""
    MESSAGE = __doc__

class UserApiKeyOwnerNotFound(Unauthorized):
    """Api key owner not found"""
    ID = "USER_API_KEY_OWNER_NOT_FOUND"
    """``str``: Error ID"""
    MESSAGE = __doc__

class InvalidOwnerApiKey(Unauthorized):
    """Owner api key is invalid"""
    ID = "INVALID_OWNER_API_KEY"
    """``str``: Error ID"""
    MESSAGE = __doc__

class MissingAuthenticationHeaders(Unauthorized):
    """Authentication headers are missing"""
    ID = "MISSING_AUTHENTICATION_HEADERS"
    """``str``: Error ID"""
    MESSAGE = __doc__

class OrderAccessDenied(Unauthorized):
    """You are not authorized to access this order"""
    ID = "ORDER_ACCESS_DENIED"
    """``str``: Error ID"""
    MESSAGE = __doc__



__all__ = (
    "SessionPasswordNeeded", 
    "UserApiKeyInvalid", 
    "UserApiKeyNotFound", 
    "UserApiKeyRevoked", 
    "UserApiKeyOwnerNotFound", 
    "InvalidOwnerApiKey", 
    "MissingAuthenticationHeaders", 
    "OrderAccessDenied", 
)

