from pathlib import Path

import json
import shutil


BASE = Path(__file__).parent.parent.parent
SOURCE = BASE / Path("compiler/errors/source.json")
DEST = BASE / Path("WolfTg/errors/exceptions")


AUTO_GENERATED_TEMPLATE = '''
# This file is auto-generated by the error generator.
# Do not edit manually.
'''.strip()

BASE_CLASS_TEMPLATE = '''
from ..api_error import ApiError

class {name}(ApiError):
    """{name}"""
    CODE = {code}
    """``int``: Error Code"""
    NAME = __doc__
'''.strip()


CLASS_TEMPLATE = '''
class {name}({base_name}):
    """{doc}"""
    ID = "{id}"
    """``str``: Error ID"""
    MESSAGE = __doc__
'''.strip()

CLASS_CTX_TEMPLATE = '''
class {name}({base_name}):
    """{doc}"""
    ID = "{id}"
    """``str``: Error ID"""
    MESSAGE = __doc__
    STORE_VALUE = False
'''.strip()

def screaming_to_pascal(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_"))

def start() -> None:
    shutil.rmtree(DEST, ignore_errors=True)
    DEST.mkdir()

    errors: dict[str, dict[str, str]] = json.loads(SOURCE.read_text(encoding="utf-8"))
    
    all_text = AUTO_GENERATED_TEMPLATE + "\n\n"

    init_text = AUTO_GENERATED_TEMPLATE + "\n\n"
    init_all_text = "__all__ = (\n"

    all_text += f"count = {sum(len(errs) - 1 for errs in errors.values())}\n\n"
    all_text += "exceptions = {\n"
    
    
    for code, exceptions in errors.items():
        module_name = f"{exceptions["_"].lower()}_{code}"
        base_name = screaming_to_pascal(exceptions["_"])

        all_text += f"    {code}: {{\n"
        all_text += f'        "_": "{base_name}", \n'

        init_text += f"from .{module_name} import * \n"
        init_all_text += f'    *{module_name}.__all__, \n'

        module_text = AUTO_GENERATED_TEMPLATE + "\n\n"
        module_text += BASE_CLASS_TEMPLATE.format_map(dict(name=base_name, code=code)) + "\n\n"

        module_all_text = "__all__ = (\n"
        module_all_text += f'    "{base_name}", \n'


        for error_id, error_doc in exceptions.items():
            if error_id == "_":
                continue

            cls_name = screaming_to_pascal(error_id)

            all_text += f'        "{error_id}": "{cls_name}", \n'

            template = (
                CLASS_CTX_TEMPLATE 
                if "{context" in error_doc
                else CLASS_TEMPLATE
            )

            module_text += template.format_map(
                {
                    "name": cls_name, 
                    "base_name": base_name, 
                    "doc": error_doc, 
                    "id": error_id
                }
            ) + "\n\n"

            module_all_text += f'    "{cls_name}", \n'
        
        module_all_text += ")"
        module_text += "\n\n" + module_all_text + "\n\n"

        (DEST / f"{module_name}.py").write_text(module_text, "utf-8")

        all_text += "    }, \n"

    all_text += "}" + "\n\n"

    (DEST / "all.py").write_text(all_text, "utf-8")

    init_all_text += ")"
    init_text += "\n\n" + init_all_text + "\n\n"

    (DEST / "__init__.py").write_text(init_text, "utf-8")



if __name__ == "__main__":
    start()